### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ternera**
I cleaned up some grammatical errors and formatting issues.

Closes #  n/a

## 💸 TL;DR

I found a broken link in the Readme. I changed the security report link to direct to Reddit's Hackerone page for easy access, and I fixed a grammatical error that I noticed.
[CI SKIP]

## 📜 Details
[Design Doc]()

[Jira]()

## ✅ Checks

- [ ] CI tests (if present) are passing
- [ ] Adheres to code style for repo
- [ ] Contributor License Agreement (CLA) completed if not a Reddit employee

### CODE REVIEW

**Comment by ternera** [comment]
Any possibility of getting this merged?

**Comment by ternera** [comment]
@niedzielski any update on getting this merged?

**Comment by ternera** [comment]
> sorry, @ternera! let me rustle up a second reviewer and we'll get this merged 👍

Great, thank you! I think I accidentally closed this when I synced my forked version, but hopefully you can reopen it. :)

**Comment by ternera** [comment]
Or I can reopen it.

**Comment by niedzielski** [comment]
can you try? sorry, was your original PR just [5bf75f8](https://github.com/reddit/devvit/commit/5bf75f8a29ba4806693aca5ebc02e45dc2b779af)? if so I think you can do something like this:

```
$ git fetch origin main
$ git checkout origin/main
$ git cherry-pick 5bf75f8
$ git checkout -b docs-tweak-lifecycle
$ git push origin docs-tweak-lifecycle
# open new PR.
```

**Comment by ternera** [comment]
> can you try? sorry, was your original PR just [5bf75f8](https://github.com/reddit/devvit/commit/5bf75f8a29ba4806693aca5ebc02e45dc2b779af)? if so I think you can do something like this:
> 
> ```
> $ git fetch origin main
> $ git checkout origin/main
> $ git cherry-pick 5bf75f8
> $ git checkout -b docs-tweak-lifecycle
> $ git push origin docs-tweak-lifecycle
> # open new PR.
> ```

I ended up just opening a new PR. #127

**Pull request closed without merging**
